version: '3.9'

networks:
  net:
    driver: bridge

services:
  chromadb:
    image: chromadb/chroma:latest
    volumes:
      - C:/Users/danie/Desktop/CIDDL/db:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
      - ALLOW_RESET=TRUE # Allows entire deletion of DB
    ports:
      - 8000:8000
    networks:
      - net
